spring:
  data:
    mongodb:
      auto-index-creation: true
      username: admin
      password: pass
      database: smart
      port: 27018
      host: localhost
      authentication-database: admin
  rabbitmq:
    host: localhost
    password: mypassword
    port: 5672
    username: myuser